### PR TITLE
Implement hbbft_perf for JSONRPC.

### PR DESCRIPTION
**Pull request by ke6jjj**
Implement the `hbbft_perf` for JSON/RPC use, as requested in
helium/miner #873.

A large portion of this code originally lived entirely within
`miner_cli_hbbft.erl`, so rather than duplicate it, the essential
information gathering now happens in `miner_util.erl` (per Evan's
suggestion) and is then parsed and formatted in different ways
by the CLI (`miner_cli_hbbft.erl`) and the JSON/RPC handler
(`miner_jsronrpc_hbbft.erl`).

### CODE REVIEW

**Comment by madninja** [comment]
@ke6jjj could you rebase your branch? It looks good otherwise 👍🏻

**Comment by ke6jjj** [comment]
Rebased.

**Comment by Vagabond** [comment]
rebase looks wrong

**Comment by ke6jjj** [comment]
oh, it's totally screwed up. :( I know.

**Comment by ke6jjj** [comment]
I think if I just undo commit 552cb75 we might just fix it. Stand by.

**Comment by ke6jjj** [comment]
This still doesn't look any better.

**Comment by ke6jjj** [comment]
I am going to abandon this PR and issue a new one from a new branch.

**Pull request closed without merging**
