### PR TITLE
Fix Docker image build break

### PR DESCRIPTION
**Pull request by fvasquez**
[lrascao/rebar3_gpb_plugin](https://github.com/lrascao/rebar3_gpb_plugin) released version `2.16.0` 7 days ago. [helium/erlang-libp2p](https://github.com/helium/erlang-libp2p) requires version `2.15.0` of `rebar3_gpb_plugin`.

### CODE REVIEW

**Comment by lthiery** [comment]
This didn't work for me locally: 
```
$ docker run --env REGION_OVERRIDE=US915 --restart always --publish 1775:1680/udp --publish 1776:1681/udp --publish 44204:44158/tcp --name miner --mount type=bind,source=/home/louis/miner_data,target=/var/data helium:miner-test

Exec: /usr/local/lib/erlang/erts-10.7.1/bin/erlexec -noshell -noinput +Bd -boot /opt/miner/releases/0.1.0/start -mode embedded -boot_var ERTS_LIB_DIR /usr/local/lib/erlang/lib -config /opt/miner/releases/0.1.0/sys.config -args_file /opt/miner/releases/0.1.0/vm.args -- foreground
Root: /opt/miner
/opt/miner
/opt/miner/bin/miner: exec: line 722: /usr/local/lib/erlang/erts-10.7.1/bin/erlexec: not found
```

**Comment by lthiery** [comment]
Did you get a working image from this @fvasquez ?

**Comment by fvasquez** [comment]
@lthiery the Docker image that I built locally seems to run on my machine.

```
frank@shannon:~$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
helium              miner               bb8dc7df1405        16 hours ago        187MB
<none>              <none>              1ce5294150e9        16 hours ago        885MB
<none>              <none>              06133d24dd22        17 hours ago        490MB
<none>              <none>              76caa2e79815        17 hours ago        490MB
<none>              <none>              38f3487f0503        17 hours ago        490MB
<none>              <none>              6cd87e87a26a        17 hours ago        490MB
<none>              <none>              5209f5a74a6b        17 hours ago        490MB
<none>              <none>              52889aee1974        17 hours ago        490MB
erlang              22.3.2-alpine       807bd876cbf4        3 months ago        68.9MB
frank@shannon:~$ docker run -d \
>   --env REGION_OVERRIDE=US915 \
>   --restart always \
>   --publish 1680:1680/udp \
>   --publish 44158:44158/tcp \
>   --name mn \
>   --mount type=bind,source=/home/frank/miner_data,target=/var/data \
>   bb8dc7df1405
cdd8a192d214895f11c4c19e844000bd89fb8e14d693f421ed52e178ba20d7e4
frank@shannon:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                              NAMES
cdd8a192d214        bb8dc7df1405        "/opt/miner/bin/mine…"   7 seconds ago       Up 6 seconds        0.0.0.0:1680->1680/udp, 0.0.0.0:44158->44158/tcp   mn
```

**Comment by lthiery** [comment]
Does it stay up for longer than 6 seconds? Are you able to resolve at 
`docker exec <NAME> miner info height`
?

**Comment by fvasquez** [comment]
```
frank@shannon:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                              NAMES
cdd8a192d214        bb8dc7df1405        "/opt/miner/bin/mine…"   18 minutes ago      Up 18 minutes       0.0.0.0:1680->1680/udp, 0.0.0.0:44158->44158/tcp   mn
frank@shannon:~$ ls ~/miner_data/
000011.log     blockchain_swarm  IDENTITY   LOCK  LOG.old.1597424071170177  miner           OPTIONS-000013
blockchain.db  CURRENT           ledger.db  LOG   MANIFEST-000010           OPTIONS-000010
frank@shannon:~$ docker exec cdd8a192d214 miner info height
11686		453784
```

**Comment by lthiery** [comment]
Sweet. Let's ship it then and see if buildkite cranks out good images again.

I'll assume my local docker build is the issue.

**Pull request merged**
