### PR TITLE
countries: update frequencies as per LoRa alliance

### PR DESCRIPTION
**Pull request by shawaj**
update frequencies as per lora alliance specification https://lora-alliance.org/wp-content/uploads/2020/11/rp_2-1.0.1.pdf

Change-type: patch
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

### CODE REVIEW

**Comment by shawaj** [comment]
relates to #654

**Comment by shawaj** [comment]
cc @Vagabond and @michaeldjeffrey

**Comment by chickenjoymeal** [comment]
https://explorer.helium.com/hotspots/112jejbZ2rxat2YCYvvfrG1jDfkRxSp2XsZHnaP84NwQKSKtVgd4

Hi these are the first 4 hotspots in the PH, I believe it is frequency 915? Is that the correct details?

**Comment by Vagabond** [comment]
We're currently reworking how regions work in the miner (we plan to ship a lookup table rather than call out to the API for location resolution) which is why we haven't taken action on this.

**Comment by shawaj** [comment]
@Vagabond ah ok, no problem. Do you have any idea when this might be completed? 

And is there anything we can help with here at all?

**Comment by Vagabond** [comment]
We have some issues with handling the AS923 sub regions, but I have taken the rest of this patch for now.

**Comment by chickenjoymeal** [comment]
Hi what’s the time line for Helium to choose an official frequency for the philippines?

**Comment by shawaj** [comment]
superseded by #772

**Comment by Edwin102576** [comment]
Hello, I just want to follow up the plotted frequency here in the Philippines.

**Comment by chickenjoymeal** [comment]
Hi yes please follow up on the philippines :)

**Comment by shawaj** [comment]
@Edwin102576 @chickenjoymeal you can check #772 it's AS923-3

**Comment by Edwin102576** [comment]
Thank you so much for the reply

**Comment by khachoanh** [comment]
I am ordering sensecap M1 device, frequency code is AU915, can it be used in Vietnam, please reply me soon

**Pull request closed without merging**
