### PR TITLE
Update Readme for Erlang OTP 23.

### PR DESCRIPTION
**Pull request by philltran**
Updating Readme for current supported version of Erland OTP.

### CODE REVIEW

**Comment by Vagabond** [comment]
It would be nice to say we support OTP 22 and 23 (and there's just a couple small changes outstanding for OTP 24) rather than specifying an exact version.

**Comment by philltran** [comment]
I updated the PR to read: 

> Miner has been tested against Erlang OTP 22 and 23. Follow [this PR](https://github.com/helium/miner/pull/655) for progress on Erlang OTP 24 support.

**Comment by philltran** [comment]
There is not a raspian version for OTP 23. Should I use the Ubuntu instructions?
https://www.erlang-solutions.com/downloads/

**Comment by Vagabond** [comment]
Ugh, I'm not sure what's best to do there. OTP 22 would be ok as well.

**Review by evanmcc — APPROVED** [review]

**Pull request merged**
