### PR TITLE
bump to blockchain core version with txn mgr cache as records

### PR DESCRIPTION
**Pull request by andymck**
Update test to account for txn mgr's txn_list returning a map of txns ( key: txn, value: TxnData )

tweak some test timers for better stability

Associated blockchain core pr: 

https://github.com/helium/blockchain-core/pull/431

### CODE REVIEW

**Comment by Vagabond** [comment]
```
%%% miner_payment_txn_SUITE ==> dependent_payment_test: FAILED
```
Looks worth investigating @andymck

**Comment by andymck** [comment]
will take a look @Vagabond

**Comment by Vagabond** [comment]
if buildkite goes green, can you merge these branches up?

**Comment by Vagabond** [comment]
after bumping the dep to point at latest core master

**Comment by andymck** [comment]
@Vagabond will do

**Pull request merged**
