### PR TITLE
update for lora spec RP002-1.0.3

### PR DESCRIPTION
**Pull request by shawaj**
update the list for lora spec RP002-1.0.3 https://lora-alliance.org/wp-content/uploads/2021/05/RP-2-1.0.3.pdf

Change-type: patch
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

### CODE REVIEW

**Comment by shawaj** [comment]
Relies on https://github.com/helium/sx1302_hal/pull/15

**Review by vihu — APPROVED** [review]
Thanks @shawaj !

**Review by JayKickliter — APPROVED** [review]

**Review by JayKickliter — CHANGES_REQUESTED** [review]
I'm terribly sorry, but could you please rename the AS923 regions to use underscores instead of dashes? And I'm extra-sorry if you anyone asked you to do opposite at any time in the past.

See https://github.com/helium/sx1302_hal/pull/16 for rationale

**Comment by shawaj** [comment]
@JayKickliter no probs...on it now. Nobody asked me to do slashes, just took it from what LoRa did really :-)

**Comment by shawaj** [comment]
@JayKickliter all done now 👍

**Review by JayKickliter — APPROVED** [review]

**Comment by JayKickliter** [comment]
Blocked by https://github.com/helium/proto/pull/81

**Comment by JayKickliter** [comment]
There's some debugging needed in blockchain-core that hasn't made its way up to miner yet, but would it wanted to propagate the protobuf changes. So this PR will have to wait a little longer.

**Comment by shawaj** [comment]
Nice thanks @vihu @JayKickliter

**Comment by Jperl2021** [comment]
Hey guys, I'm from Israel and very enthusiastic about the Helium network project. I have ordered 3 Bobcat miners 969Mhz to test out in Israel.
I checked the local countries and saw that the 868 frequency is the standard and not the 915, what are your thoughts, what would work better?
Did anybody else purchase devices to test them out?
I contacted the Israeli frequency office in the communication department, and they said that a frequency (868) is not available. It might be in the future, and they invited me to place a commercial request that get authorization. On the mean while I will consider that conduct a pilot to see if the network is even active here.

**Comment by shawaj** [comment]
> Hey guys, I'm from Israel and very enthusiastic about the Helium network project. I have ordered 3 Bobcat miners 868Mhz to test out in Israel.
> I checked the local countries and saw that the 868 frequency is the standard and not the 915, what are your thoughts, what would work better?
> Did anybody else purchase devices to test them out?
> I contacted the Israeli frequency office in the communication department, and they said that a frequency (868) is not available. It might be in the future, and they invited me to place a commercial request that get authorization. On the mean while I will consider that conduct a pilot to see if the network is even active here.

The correct frequency plan for Israel is AS923-4 as you will see in the PDF linked in the first post.

**Comment by Jperl2021** [comment]
Thanks, I saw, but please help me out here. I saw the Helium Hotspots are sold with two frequencies:
1. 915 MHz for USA.
2. 868 MHz for EU.
*I am not a tech guy. What am I missing here? What Hotspot would work in Israel, the USA one or the EU one?

**Comment by JayKickliter** [comment]
US915 hardware should be identical and work in Israel (AS923). Technically it should be certified by Israel’s communication regulatory body, but I’m not familiar with those details.

**Comment by shawaj** [comment]
@Jperl2021 they differ from manufacturer to manufacturer. Your best bet is going to the [Helium Discord server](https://discord.gg/helium) and asking in the various vendor channels if they support AS923-4 frequency.

Additionally, if you ask one of the moderators or admins in the Discord server to create an #il-israel channel then you can discuss in there also with others from Israel.

**Comment by Jperl2021** [comment]
Thank you guys!!

**Comment by t0mmyz7** [comment]
@shawaj thanks for working on adding RP1.0.3 and AS923-4 support to the network.
I open an issue about AS923-4 not listed in miner_lora_throttle.erl
It should be handled there as well no? https://github.com/helium/miner/issues/1094

**Comment by Adiargov** [comment]
> @shawaj thanks for working on adding RP1.0.3 and AS923-4 support to the network. I open an issue about AS923-4 not listed in miner_lora_throttle.erl It should be handled there as well no? #1094

Can we get an ETA for update? Entire state is not able to communicate.
Thanks for your help

**Comment by tzacha** [comment]
yep ..
it will realy apprisiated to get this issue resolved soon
 currently miners cant witness other miners. so there is no insentive to extend the network.
thanks in advance

**Pull request merged**
