### PR TITLE
Update frequency plans

### PR DESCRIPTION
**Pull request by ryanteck**
There was a few mistakes made in the frequency plans in the last update. 

I've re-gone through the document at https://lora-alliance.org/wp-content/uploads/2020/11/RP_2-1.0.2.pdf and believe the changes included are correct.

### CODE REVIEW

**Comment by Nathaniel0202** [comment]
Good afternoon, does anyone know if Trinidad and Tobago uses US915 or AU915?

**Comment by shawaj** [comment]
@ryanteck FYI there's an updated doc now 
[RP-2-1.0.3.pdf](https://github.com/helium/miner/files/6494299/RP-2-1.0.3.pdf)

**Comment by ryanteck** [comment]
I think with the recent conflicts is Israel really the best to add in though @shawaj ?

**Comment by shawaj** [comment]
@ryanteck not sure how that really effects/relates to whether we include new specs from lora alliance here personally?

In any case, seemed there were some other changes in that new spec in any case, and needed to update to add as923 variants too so have proposed #772

**Comment by shawaj** [comment]
@ryanteck think this can be closed as #772 now merged

**Comment by ryanteck** [comment]
I believe there was quite a few issues in it previously though. So will leave it open.

**Comment by shawaj** [comment]
@ryanteck FYI I went through the new doc from start to finish to check them all. So shouldn't be any errors anymore as far as I can see.

Also updated the Helium docs to reflect it as well in https://github.com/helium/docs/pull/345

**Pull request closed without merging**
