### PR TITLE
Refactor hbbft_perf, renaming some confusing variables.

### PR DESCRIPTION
**Pull request by ke6jjj**
Refactor and clean up miner_util:hbbft_perf/0 so that it returns
a map, rather than a giant tuple, and rename some of its internal
variables so that they are easier to understand (e.g. "Start0" is
now "ElectionStart").

Also clean up the JSON/RPC and the CLI `hbbft perf` endpoints as
well.

This change also fixes an issue where the `hbbft_perf` JSON/RPC
call was returning singleton lists for the `performance` and `tenure`
fields for each validator.

### CODE REVIEW

**Review by mrallen1 — APPROVED** [review]

**Comment by mrallen1** [comment]
:shipit:

**Comment by mrallen1** [comment]
It'd be nice to squash these commits before merge, tho

**Comment by ke6jjj** [comment]
Which commits? Is is screwed up?

**Comment by abhay** [comment]
> Which commits? Is is screwed up?

Rebase and fixup/squash commits so there's just one commit for entire PR.

**Comment by evanmcc** [comment]
closing in favor of #1000, which is the same code rebased and squashed.

**Pull request closed without merging**
